include ./rules/Makefile.silent
include ./rules/Makefile.settings

ifndef GIT_DEF
GIT_DEF = 1

GIT ?= git

GIT_DIFF_CMD ?= $(GIT) diff

.PHONY: git-diff
git-diff:
ifeq (,$(SILENT))
	@if ! $(GIT_DIFF_CMD) --quiet; then \
		printf 'Found changes on local workspace. '; \
		printf 'Please run `make generate fix` and commit the changes.\n'; \
		exit 1; \
	fi
else
	$(GIT_DIFF_CMD) --quiet
endif

endif
